import type { Metadata } from 'next'
import Header from '@/components/header'
import RightBar from '@/components/rightbar'
import LeftBar from '@/components/leftbar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function Layout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
    return (
        <>
            <div className="flex">
                <LeftBar />
                <main className="mx-auto max-w-4xl w-full">
                    <Header />
                    {children}
                </main>
                <RightBar />
            </div>
            {modal}
        </>
    )
}
