import type { Metadata } from 'next'
import '@/styles/globals.css'
import Header from '@/components/header'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Header/>
        <main className='mx-auto max-w-5xl'>
          {children}
        </main>
      </body>
    </html>
  )
}
