import '@/styles/globals.css'

import Providers from '@/components/provider'
import { Toaster } from 'react-hot-toast'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Toaster />
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
